
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Allows the mod to try to remap and convert other blocks and items from other compat mods that have been uninstalled from one world. This was made so one can uninstall such mods seamlessly having their blocks converted into Evety Compat counterparts
	remap_other_mods = true
	#Clears out and remaps all blocks registered by this mod belonging to uninstalled wood types to air or oak wood
	remap_self = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true

[wood_type]

	[wood_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		crimson = true
		warped = true

	[wood_type.blue_skies]
		bluebright = true
		starlit = true
		frostbright = true
		lunar = true
		dusk = true
		maple = true
		cherry = true

	[wood_type.architects_palette]
		twisted = true

	[wood_type.mysticalworld]
		charred = true

	[wood_type.byg]
		aspen = true
		baobab = true
		blue_enchanted = true
		cherry = true
		cika = true
		cypress = true
		ebony = true
		fir = true
		green_enchanted = true
		holly = true
		jacaranda = true
		mahogany = true
		mangrove = true
		maple = true
		pine = true
		rainbow_eucalyptus = true
		redwood = true
		skyris = true
		willow = true
		witch_hazel = true
		zelkova = true
		sythian = true
		palm = true
		lament = true
		bulbis = true
		nightshade = true
		ether = true
		imparius = true

	[wood_type.valhelsia_structures]
		lapidified_jungle = true

	[wood_type.quark]
		blossom = true
		azalea = true

[leaves_type]

	[leaves_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		azalea = true
		flowering_azalea = true

	[leaves_type.blue_skies]
		bluebright = true
		starlit = true
		frostbright = true
		lunar = true
		dusk = true
		maple = true
		cherry = true
		crescent_fruit = true

	[leaves_type.architects_palette]
		twisted = true

	[leaves_type.byg]
		aspen = true
		baobab = true
		blue_enchanted = true
		cika = true
		cypress = true
		ebony = true
		fir = true
		green_enchanted = true
		holly = true
		jacaranda = true
		mahogany = true
		mangrove = true
		maple = true
		pine = true
		rainbow_eucalyptus = true
		redwood = true
		skyris = true
		willow = true
		witch_hazel = true
		zelkova = true
		palm = true
		lament = true
		nightshade = true
		ether = true
		araucaria = true
		blooming_witch_hazel = true
		blue_spruce = true
		brown_birch = true
		brown_oak = true
		brown_zelkova = true
		flowering_orchard = true
		flowering_palo_verde = true
		holly_berry = true
		indigo_jacaranda = true
		flowering_jacaranda = true
		flowering_indigo_jacaranda = true
		joshua = true
		ripe_joshua = true
		orange_birch = true
		orange_oak = true
		orange_spruce = true
		orchard = true
		palo_verde = true
		pink_cherry = true
		red_birch = true
		red_maple = true
		red_oak = true
		red_spruce = true
		ripe_orchard = true
		silver_maple = true
		green_apple_skyris = true
		white_cherry = true
		yellow_birch = true
		yellow_spruce = true
		withering_oak = true
		flowering_nightshade = true
		firecracker = true

	[leaves_type.culturaldelights]
		avocado = true

	[leaves_type.quark]
		blue_blossom = true
		lavender_blossom = true
		orange_blossom = true
		pink_blossom = true
		yellow_blossom = true
		red_blossom = true

